'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FacultyEvalPage

    '''<summary>
    '''lblStudentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudentName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEvaluatorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEvaluatorName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProgramName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProgramName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RBFEQ1S1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ1S1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ1S2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ1S2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ1S3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ1S3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ1S4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ1S4 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ1S5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ1S5 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ1SNA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ1SNA As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ2S1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ2S1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ2S2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ2S2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ2S3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ2S3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ2S4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ2S4 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ2S5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ2S5 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ2SNA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ2SNA As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ3S1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3S1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ3S2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3S2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ3S3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3S3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ3S4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3S4 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ3S5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3S5 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RBFEQ3SNA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3SNA As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TextArea1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextArea1 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RBLPassFail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBLPassFail As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''btnSubmitFacultyEval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitFacultyEval As Global.System.Web.UI.WebControls.Button
End Class
