'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StudentEval_LandingPage
    
    '''<summary>
    '''lblStudentRotationalPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudentRotationalPeriod As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblStudentRotationalProgram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudentRotationalProgram As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblStudentRotationalLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudentRotationalLocation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnContinueEval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinueEval As Global.System.Web.UI.WebControls.Button
End Class
